### ISSUE TITLE
Add zoweb to contributors

### ISSUE THREAD

**Issue by Zoweb** [AssaultBird2454/Virtual-Pokemon-Tabletop#38]
I need to add myself to the list of contributors. Will probably add other contributors while I'm at it.

Linked to #39

**Comment by AssaultBird2454** [comment]
nice issue

**Comment by Zoweb** [comment]
The issue should close when the pull request closes? You don't need to close it.

**Comment by Zoweb** [comment]
The issue is technically not fixed yet.
